from hashlib import md5, sha1 

def custom_hash_f(element, i, length):
  h1 = int(md5(element.encode('ascii')).hexdigest(), 16) # first hash generated by md5
  h2 = int(sha1(element.encode('ascii')).hexdigest(),16) # second hash generated by sha1
  return (h1 + i*h2) % length # (h1 + i*h2)%length 
